"""Initial migration.

Revision ID: 993d8014c94e
Revises: 35d728c8d24b
Create Date: 2024-04-14 13:51:48.838336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993d8014c94e'
down_revision = '35d728c8d24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_comment', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
