"""Initial migration.

Revision ID: a6855c20dc9a
Revises: 5c4f089caad0
Create Date: 2024-04-13 19:37:40.915593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6855c20dc9a'
down_revision = '5c4f089caad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint('unique_lesson_per_course_unit_number', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_lesson_per_course_unit_number', ['course_id', 'unit_id', 'number'])

    # ### end Alembic commands ###
